<?php
if (stristr($_SERVER["SCRIPT_NAME"], "config.php")) {
    Header("Location: index.php");
    die();
}

//automatically generated by install script

//--------- DBASE CONFIGURATION --------->
$dbhost = "localhost";                       /* "localhost" */
$dbuname = "pnc";                     /* "database user name" */
$dbpass = "password";                       /* "database password" */
$dbname = "pnc";                       /* "database name" */

//--------- PNC  CONFIGURATION ---------->
$prefix = "pnc";
$user_prefix = "pnc";
$dbtype = "MySQL";
$sitekey = "kjhdskljndsf_OPJILH";
$gfx_chk = "0";
$subscription_url = "";
$admin_file = "admin";
//vwarfoldername
$vwarmodname ="vwar";

/************************************************************************/
/* Database and System Configuration                        INFORMATION */
/*                                                                      */
/* dbhost:       SQL Database Hostname                                  */
/* dbuname:      SQL Username                                           */
/* dbpass:       SQL Password                                           */
/* dbname:       SQL Database Name                                      */
/* $prefix:      Your Database tables prefix                            */
/* $user_prefix: Your Users Database tables prefix (To share it)        */
/* $dbtype:      Your Database Server type. Supported servers are:      */
/*               MySQL, mysql4, postgres, mssql, oracle, msaccess,      */
/*               db2 and mssql-odbc                                     */
/*               Be sure to write it exactly as above, case SeNsItIvE!  */
/* $sitekey:    Security Key. CHANGE it to whatever you want, as long   */
/*               as you want. Just dont use quotes.                     */
/* $gfx_chk:    Set the graphic security code on every login screen,    */
/*      You need to have GD extension installed:                        */
/*      0: No check                                                     */
/*      1: Administrators login only                                    */
/*      2: Users login only                                             */
/*      3: New users registration only                                  */
/*      4: Both, users login and new users registration only            */
/*      5: Administrators and users login only                          */
/*      6: Administrators and new users registration only               */
/*      7: Everywhere on all login options (Admins and Users)           */
/*      NOTE: If you arent sure set this value to 0                     */
/* $subscription_url : If you manage subscriptions on your site, you    */
/*                    must write here the url of the subscription       */
/*                    information/renewal page. This will send by       */
/*                     email if set.                                    */
/* $admin_file : Administration panel filename. "admin" by default for  */
/*               "admin.php". To improve security please rename the file*/
/*               "admin.php" and change the $admin_file value to the new*/
/*                filename (without the extension .php)                 */
/*                                                                      */
/************************************************************************/
/* You finished to configure the Database. Now you can change all you   */
/* want in the Administration panel. To enter just launch you web       */
/* browser pointing to http://www.YOURSITE.com/admin.php                */
/*                                                                      */
/* Remeber to go to Settings section where you can configure your new   */
/* site. In that menu you can change all you need to change.            */
/*                                                                      */
/* Congratulations! you now have successfully installed                 */
/* PNC4.5                                                          */
/************************************************************************/
/*   Thankyou for choosing PNC3.0.2: Expect to be impressed.           */
/************************************************************************/
// Do not touch anything below this line unless you know what you are doing
$reasons = array("As Is","Offtopic","Flamebait","Troll","Redundant","Insightful","Interesting","Informative","Funny","Overrated","Underrated");
$badreasons = 4;
$AllowableHTML = array("b"=>1,"i"=>1,"u"=>1,"div"=>2,"a"=>2,"em"=>1,"br"=>1,"strong"=>1,"blockquote"=>1,"tt"=>1,"li"=>1,"ol"=>1,"ul"=>1);
$CensorList = array("fuck","cunt","fucker","fucking","pussy","cock","c0ck","cum","twat","clit","bitch","fuk","fuking","motherfucker");
$tipath = "images/topics/";
?>