<?php
/**********************************************************************************************/
/* PNC 4.5 Edition                                            PORT LIST                       */
/*                                                                                            */
/* Copyright (c) 2006 - 2009 by http://phpnuke-clan.net                                       */
/*  PHPNUKE-CLAN - SUPPORT                (support@phpnuke-clan.net)                          */
/**********************************************************************************************/

// DO NOT TOUCH THE FOLLOWING COPYRIGHT CODE. YOU'RE JUST ALLOWED TO CHANGE YOUR "OWN"
// MODULE'S DATA (SEE ABOVE) SO THE SYSTEM CAN BE ABLE TO SHOW THE COPYRIGHT NOTICE
// FOR YOUR MODULE/ADDON. PLAY FAIR WITH THE PEOPLE THAT WORKED CODING WHAT YOU USE!!
// YOU ARE NOT ALLOWED TO MODIFY ANYTHING ELSE THAN THE ABOVE REQUIRED INFORMATION.
// AND YOU ARE NOT ALLOWED TO DELETE THIS FILE NOR TO CHANGE ANYTHING FROM THIS FILE IF
// YOU'RE NOT THIS MODULE'S AUTHOR.

function show_portlist() {
    //$module_name = basename(dirname(__FILE__));
    //$module_name = eregi_replace("_", " ", $module_name);
    $module_name = "SQuery Admin";
	echo "<html>\n"
	."<body bgcolor=\"#F6F6EB\" link=\"#363636\" alink=\"#363636\" vlink=\"#363636\">\n"
	."<title>$module_name: Game Query Ports</title>\n"
	."<font size=\"2\" color=\"#363636\" face=\"Verdana, Helvetica\">\n"
	."<center><b>The ports listed below are required to be open for the games you intend to query.</b><br>"
	."<table width=\"436\" border=\"1\">"
   ."<tr>"
   ."  <td colspan=\"2\"><div align=\"center\" class=\"style1\">Legend for Interpreting Ports</div></td>"
   ."</tr>"
   ."<tr>"
   ."  <td width=\"82\"><div align=\"center\">0</div></td>"
   ."  <td width=\"338\">The port you use to connect to the game is the query port that needs opened b your webhost</td>"
   ."</tr>"
   ."<tr>"
   ."  <td><div align=\"center\">+ (Number)</div></td>"
   ."  <td>If your game has a listing like this&quot;+18050&quot;  that means that you need to add 18050 to the port used to connect to  the game. So if you connect to a server with 33.33.45.45:28690 your  query port would be 28960 + 18050 = 47010.</td>"
   ."</tr>"
   ."<tr>"
   ."  <td><div align=\"center\">(Number)</div></td>"
   ."  <td> If the game has a listing like &quot;28960&quot; with no &quot;+&quot; then that number is simply your query port. </td>"
   ."</tr>"
   ."</table>"
   ."<br />"
   ."<table width=\"357\" border=\"0\">"
   ."  <tr>"
   ."     <th width=\"204\" scope=\"col\"><div align=\"left\">Game Name</div></th>"
   ."     <th width=\"97\" scope=\"col\"><div align=\"left\">Port Queried</div></th>"
   ."  </tr>"
   ."   <tr>"
   ."     <td>Americas Army</td>"
   ."     <td>+1</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Alien Vs Predator 2</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>BattleField:1942</td>"
   ."     <td>23000</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>BattleField: Vietnam</td>"
   ."     <td>23000</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Battlefield 2</td>"
   ."     <td>29900</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Battlefield 2 : Special Forces</td>"
   ."     <td>29900</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Call of Duty</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>CoD:United Offensive</td>"
   ."     <td>0</td>"
   ."  </tr>"
   ."   <tr>"
   ."     <td>Call of Duty 2</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Call of Duty 4</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Chaser</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Chrome</td>"
   ."     <td>+123</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>CNC Renegade</td>"
   ."     <td>25300</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Counterstrike 1.5</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Counterstrike</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Counter Strike: Source</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Descent 3</td>"
   ."     <td>+18050</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Devastation</td>"
   ."     <td>+10</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Day of Defeat: Source</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Doom 3</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>FarCry</td>"
   ."     <td>+123</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>F.E.A.R</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Global Ops</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Gore</td>"
   ."     <td>+1</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Ghost Recon AW</td>"
   ."     <td>15250</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Halo</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Heretic</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Half Life</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Half Life 2</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Half Life: CStrike</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Half Life: Condition Zero</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Half Life: Day of Defeat</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Half Life: Death Match</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Half Life: N.S</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Half Life: Opposing Fronts</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Half Life: Team Fortress</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>IL-2 Sturmovik</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>IGI2</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Jedi Knight 2</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Jedi Knight 3</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>KumaWar</td>"
   ."     <td>13242</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>MOH:AA</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>MOH:BT</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>MOH:PA</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>MOH:SH</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>MTA(GTA3)</td>"
   ."     <td>+123</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>NASCAR SimRacer</td>"
   ."     <td>-100</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>NetPanzer</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>NOLF</td>"
   ."     <td>+1</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>NOLF 2</td>"
   ."     <td>+1</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Operation Flashpoint</td>"
   ."     <td>+1</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Painkiller</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Postal 2</td>"
   ."     <td>+1</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Purge Jihad</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Quake 2</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Quake 3</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Quake 3: UT</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Quake 4</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Quake World</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Rally Masters</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Return to Castle Wolfenstein</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Return to Castle Wolfenstein: ET</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Rune</td>"
   ."     <td>+1</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Savage</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Serious Sam</td>"
   ."     <td>+1</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Serious Same 2</td>"
   ."     <td>+1</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Sin</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Soldier of Fortune</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Soldier of Fortune II</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Soldat</td>"
   ."     <td>+123</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>ST:Elite Force</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>ST:Elite Force 2</td>"
   ."     <td>0</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>StarWars: Battlefront</td>"
   ."     <td>3658</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Tactical Ops</td>"
   ."     <td>+1</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Unreal</td>"
   ."     <td>+1</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Unreal 2 XMP</td>"
   ."     <td>+10</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Unreal Tournament</td>"
   ."     <td>+1</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Unreal Tournament 2003</td>"
   ."     <td>+10</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>Unreal Tournament 2004</td>"
   ."     <td>+10</td>"
   ."   </tr>"
   ."   <tr>"
   ."     <td>VietCong</td>"
   ."     <td>+10000</td>"
   ."   </tr>"
   ." </table>"
   ."</font>\n"
   ."</body>\n"
   ."</html>";
}

show_portlist();
?>