<?php
#### Generated by Html to PHP converter By Disipal Site (www.disipal.net) ####


echo"<div align=\"center\">"
  . "<TABLE WIDTH=977 BORDER=0 CELLPADDING=0 CELLSPACING=0>"
  . "	<TR>"
  . "	  <TD COLSPAN=5 bgcolor=\"#4E4646\"><div align=\"center\"><font face=\"Geneva, Arial, Helvetica, sans-serif\"><font size=\"1\">";
footmsg();
echo"</font></font>  </div></TD>"
  . "  </TR>"
  . "	<TR>"
  . "		<TD COLSPAN=5>"
  . "			<IMG SRC=\"themes/Lexus-Blue/images/footer/footer_01.gif\" WIDTH=977 HEIGHT=16 ALT=\"\"></TD>"
  . "	</TR>"
  . "	<TR>"
  . "		<TD ROWSPAN=2>"
  . "			<a href=\"http://www.phpnuke-clan.net/\" target=\"_blank\"><IMG SRC=\"themes/Lexus-Blue/images/footer/footer_02.gif\" ALT=\"\" WIDTH=135 HEIGHT=63 border=\"0\"></a></TD>"
  . "		<TD COLSPAN=3>"
  . "			<IMG SRC=\"themes/Lexus-Blue/images/footer/footer_03.gif\" WIDTH=726 HEIGHT=21 ALT=\"\"></TD>"
  . "		<TD ROWSPAN=2>"
  . "			<a href=\"http://www.areyouserved.com/index.php?aid=pra42493\" target=\"_blank\"><IMG SRC=\"themes/Lexus-Blue/images/footer/footer_04.gif\" ALT=\"\" WIDTH=116 HEIGHT=63 border=\"0\"></a></TD>"
  . "	</TR>"
  . "	<TR>"
  . "		<TD>"
  . "			<IMG SRC=\"themes/Lexus-Blue/images/footer/footer_05.gif\" WIDTH=250 HEIGHT=42 ALT=\"\"></TD>"
  . "		<TD>"
  . "			<a href=\"http://www.minlegeplads.dk/gfx/\" target=\"_blank\"><IMG SRC=\"themes/Lexus-Blue/images/footer/footer_06.gif\" ALT=\"\" WIDTH=205 HEIGHT=42 border=\"0\"></a></TD>"
  . "		<TD>"
  . "			<IMG SRC=\"themes/Lexus-Blue/images/footer/footer_07.gif\" WIDTH=271 HEIGHT=42 ALT=\"\"></TD>"
  . "	</TR>"
  . "	<TR>"
  . "		<TD COLSPAN=5>"
  . "			<IMG SRC=\"themes/Lexus-Blue/images/footer/footer_08.gif\" WIDTH=977 HEIGHT=9 ALT=\"\"></TD>"
  . "	</TR>"
  . "</TABLE>"
  . "</div>"
 ."";
?>
