<?
session_start();
/**
Written and solely owned by Raven Web Services, LLC
Not for distribution other than by Raven Web Services, LLC
Copyright 2005,2006
Modified to install PNC4.5 by PNC team
**/
define('PNC_INST', true);
$step = $_GET['step'];
if( !isset( $_GET['step'] )) {
	$step = "";
}
$Notwrite = "";
$pncv ="4.5.0";
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>PNC<?php echo $pncv ; ?>&trade; SQL Installer</title>
<META NAME="RATING" CONTENT="GENERAL">
<META NAME="GENERATOR" CONTENT="PHP Web Host - Quality Web Hosting For All PHP Applications - Copyright (c) 2002-2006 by http://ravenphpscripts.net">
<style type="text/css">
/*<![CDATA[*/
 body.c1 {background-color:#E2E2E2}
 div.c1 {text-align: center}
 input.c1 {width:300px;}
 p.c1 {font-weight: bold}
 span.c1 {font-size:small;}
 span.c2 {color:red;font-weight:bold;}
 span.c3 {color:blue;font-weight:bold;}
 .formbutton{
/*cursor:pointer;*/
border:outset 1px #ccc;
background:#FF0000;
color:#FFFFFF;
font-weight:bold;
padding: 1px 2px;
width:300px;

}
/*]]>*/
</style>
</head>
  <body class="c1">
    <img src="PNC_logo.png" border="0" alt="" />
    <h2>
      PNC&trade; &copy; 2006, 2007 - MySQL Table Installer
    </h2>
    <span class="c2">Please note that this installer is for <u>NEW</u> installs and assumes that you want to <u>REPLACE</u> your tables and the data therein. This means that each time you run this it will <u>DROP</u> the tables and <u>DELETE</u> all data before creating new ones. This is <u>NOT</u> recoverable.</span>
    <hr />
    <p class="c1">
      <u>MySQL Database Connectivity Test Results</u>
    </p>
<?
if($step == "2") {

$filename = '../config.php';
$somecontent = '<?php
if (stristr($_SERVER["SCRIPT_NAME"], "config.php")) {
    Header("Location: index.php");
    die();
}

//automatically generated by install script

//--------- DBASE CONFIGURATION --------->
$dbhost = "'.$_POST['dbhost'].'";                       /* "localhost" */
$dbuname = "'.$_POST['dbuname'].'";                     /* "database user name" */
$dbpass = "'.$_POST['dbpass'].'";                       /* "database password" */
$dbname = "'.$_POST['dbname'].'";                       /* "database name" */

//--------- PNC  CONFIGURATION ---------->
$prefix = "'.$_POST[prefix].'";
$user_prefix = "'.$_POST[userprefix].'";
$dbtype = "'.$_POST[dbtype].'";
$sitekey = "'.$_POST[sitekey].'";
$gfx_chk = "'.$_POST[gfxchk].'";
$subscription_url = "'.$_POST[subscription_url].'";
$admin_file = "'.$_POST[admin_file].'";
//vwarfoldername
$vwarmodname ="'.$_POST[vwarmodname].'";

/************************************************************************/
/* Database and System Configuration                        INFORMATION */
/*                                                                      */
/* dbhost:       SQL Database Hostname                                  */
/* dbuname:      SQL Username                                           */
/* dbpass:       SQL Password                                           */
/* dbname:       SQL Database Name                                      */
/* $prefix:      Your Database tables prefix                            */
/* $user_prefix: Your Users Database tables prefix (To share it)        */
/* $dbtype:      Your Database Server type. Supported servers are:      */
/*               MySQL, mysql4, postgres, mssql, oracle, msaccess,      */
/*               db2 and mssql-odbc                                     */
/*               Be sure to write it exactly as above, case SeNsItIvE!  */
/* $sitekey:    Security Key. CHANGE it to whatever you want, as long   */
/*               as you want. Just dont use quotes.                     */
/* $gfx_chk:    Set the graphic security code on every login screen,    */
/*      You need to have GD extension installed:                        */
/*      0: No check                                                     */
/*      1: Administrators login only                                    */
/*      2: Users login only                                             */
/*      3: New users registration only                                  */
/*      4: Both, users login and new users registration only            */
/*      5: Administrators and users login only                          */
/*      6: Administrators and new users registration only               */
/*      7: Everywhere on all login options (Admins and Users)           */
/*      NOTE: If you arent sure set this value to 0                     */
/* $subscription_url : If you manage subscriptions on your site, you    */
/*                    must write here the url of the subscription       */
/*                    information/renewal page. This will send by       */
/*                     email if set.                                    */
/* $admin_file : Administration panel filename. "admin" by default for  */
/*               "admin.php". To improve security please rename the file*/
/*               "admin.php" and change the $admin_file value to the new*/
/*                filename (without the extension .php)                 */
/*                                                                      */
/************************************************************************/
/* You finished to configure the Database. Now you can change all you   */
/* want in the Administration panel. To enter just launch you web       */
/* browser pointing to http://www.YOURSITE.com/admin.php                */
/*                                                                      */
/* Remeber to go to Settings section where you can configure your new   */
/* site. In that menu you can change all you need to change.            */
/*                                                                      */
/* Congratulations! you now have successfully installed                 */
/* PNC4.5                                                          */
/************************************************************************/
/*   Thankyou for choosing PNC3.0.2: Expect to be impressed.           */
/************************************************************************/
// Do not touch anything below this line unless you know what you are doing
$reasons = array("As Is","Offtopic","Flamebait","Troll","Redundant","Insightful","Interesting","Informative","Funny","Overrated","Underrated");
$badreasons = 4;
$AllowableHTML = array("b"=>1,"i"=>1,"u"=>1,"div"=>2,"a"=>2,"em"=>1,"br"=>1,"strong"=>1,"blockquote"=>1,"tt"=>1,"li"=>1,"ol"=>1,"ul"=>1);
$CensorList = array("fuck","cunt","fucker","fucking","pussy","cock","c0ck","cum","twat","clit","bitch","fuk","fuking","motherfucker");
$tipath = "images/topics/";
?>';

	// Let's make sure the file exists and is writable first.
	if (is_writable($filename)) {
		// In our example we're opening $filename in append mode.
		// The file pointer is at the bottom of the file hence
		// that's where $somecontent will go when we fwrite() it.
		if (!$handle = fopen($filename, 'w')) {
			echo "Cannot open file ($filename)";
			exit;
		}

		// Write $somecontent to our opened file.
		if (fwrite($handle, $somecontent) === FALSE) {
			echo "Cannot write to file ($filename)";
			exit;
		}

		fclose($handle);
		//  Header("Location: $PHP_SELF?step=3");
	} else {
		$Notwrite = "But the file is not writable, please chmod it to 777.";
	}
}

ini_set('display_errors','on');
ini_set('mysql.connect_timeout',120);
$dbCheck = array();
$nukeConfigFile = "../config.php";
if (!file_exists($nukeConfigFile)) {rnInstallErr(1); die();}
echo '<b>config.php file found!<span class="c2"> '.$Notwrite.'</span /></b><br />';

require_once("../config.php");
$conn = @mysql_connect($dbhost,$dbuname,$dbpass);
if (!$conn)  {rnInstallErr(2); die();}
echo '<b>Successfully connected to '.$dbhost.' as user '.$dbuname.' and assigned password!</b><br />';
$db = mysql_select_db($dbname);
if (!$db)  {rnInstallErr(3); die();}
echo '<b>Database '.$dbname.' found!</b><br />';

$sql = "CREATE TABLE INSTALL (`id` int(9) NOT NULL auto_increment,      PRIMARY KEY (id));";
$rc = @mysql_query($sql);
if (!$rc)  {
$sql2= "DROP TABLE IF EXISTS INSTALL;";
$rc2 = @mysql_query($sql2);
rnInstallErr(4); die();
}
$sql2= "DROP TABLE IF EXISTS INSTALL;";
$rc2 = @mysql_query($sql2);

function rnInstallErr($errNum) {
        if ($errNum==1) die('<span style="font-weight:bold;color:red;">It appears that your nuke config.php file is either missing or the permissions are not allowing it to be accessed.  Please verify the config.php is in your root folder where your mainfile.php is located and has permissions of at least 777.  Then try running the Install script again.</span>');

        elseif ($errNum==2) {
        require_once("../config.php");
        global $dbhost, $dbuname, $dbpass, $dbname, $prefix, $user_prefix, $sitekey, $subscription_url, $admin_file, $gfx_chk, $vwarmodname, $pncv;
        ?>
<div align="center">
  <font size="5" face="Geneva, Arial, Helvetica, sans-serif"><strong><font size="6"><?php echo $pncv ; ?></font></strong></font><font size="6" face="Geneva, Arial, Helvetica, sans-serif"></font><font face="Geneva, Arial, Helvetica, sans-serif"><br>
  <font size="2"><strong>(Auto-Installer)</strong></font><br>
  For more information or help, read the <a href="http://www.phpnuke-clan.net/guide/PNC4/" target="_blank">Installation Guide</a>! </font></div>
<form name="INST" method="post" action="<? echo $_SERVER['PHP_SELF']; ?>?step=2">
  <div align="center">
    <table width="484" border="1">
      <tr bgcolor="#FFFFCC">
        <td width="188"><div align="right"><strong><font face="Geneva, Arial, Helvetica, sans-serif">Host:</font></strong></div></td>
        <td width="280"><font face="Geneva, Arial, Helvetica, sans-serif">
          <input name="dbhost" type="text" id="dbhost" value="<?php echo "$dbhost"; ?>">
        </font></td>
      </tr>
      <tr>
        <td><div align="right"><strong><font face="Geneva, Arial, Helvetica, sans-serif">User Name:</font></strong></div></td>
        <td><font face="Geneva, Arial, Helvetica, sans-serif">
          <input name="dbuname" type="text" id="dbuname" value="<?php echo "$dbuname"; ?>">
        </font></td>
      </tr>
      <tr bgcolor="#FFFFCC">
        <td><div align="right"><strong><font face="Geneva, Arial, Helvetica, sans-serif">Password:</font></strong></div></td>
        <td><font face="Geneva, Arial, Helvetica, sans-serif">
          <input name="dbpass" type="PASSWORD" id="dbpass" value="<?php echo "$dbpass"; ?>">
        </font></td>
      </tr>
      <tr>
        <td><div align="right"><strong><font face="Geneva, Arial, Helvetica, sans-serif">Database Name:</font></strong></div></td>
        <td><font face="Geneva, Arial, Helvetica, sans-serif">
          <input name="dbname" type="text" id="dbname" value="<?php echo "$dbname"; ?>">
        </font></td>
      </tr>
            <tr>
        <td><div align="right"><strong><font face="Geneva, Arial, Helvetica, sans-serif">Prefix:</font></strong></div></td>
        <td><font face="Geneva, Arial, Helvetica, sans-serif">
          <input name="prefix" type="text" id="prefix" value="<?php echo "$prefix"; ?>">
          <br>
          <font color="#FF0000" size="2">(only change if you manually ) </font></font></td>
      </tr>
      <tr bgcolor="#FFFFCC">
        <td><div align="right"><strong><font face="Geneva, Arial, Helvetica, sans-serif">User Prefix:</font></strong></div></td>
        <td><font face="Geneva, Arial, Helvetica, sans-serif">
          <input name="userprefix" type="text" id="userprefix" value="<?php echo "$user_prefix"; ?>">
        </font></td>
      </tr>
      <tr>
        <td><div align="right"><strong><font face="Geneva, Arial, Helvetica, sans-serif">Database Type:</font></strong></div></td>
        <td><font face="Geneva, Arial, Helvetica, sans-serif">
          <select name="dbtype" id="dbtype">
            <option value="MySQL" selected>MySQL</option>
            <option value="mysql4">mysql4</option>
            <option value="postgres">postgres</option>
            <option value="mssql">mssql</option>
            <option value="oracle">oracle</option>
            <option value="msaccess">msaccess</option>
            <option value="db2">db2</option>
            <option value="mssql-odbc">mssql-odbc</option>
          </select>
          <br>
          <font color="#FF0000" size="2">(Usually MySQL)</font></font></td>
      </tr>
      <tr bgcolor="#FFFFCC">
        <td><div align="right"><strong><font face="Geneva, Arial, Helvetica, sans-serif">Security Key:</font></strong></div></td>
        <td><font face="Geneva, Arial, Helvetica, sans-serif">
          <input name="sitekey" type="text" id="sitekey" value="<?php echo "$sitekey"; ?>">
          <br>
          <font color="#FF0000" size="2">CHANGE it to whatever you want, as long as you want. Just dont use quotes. </font></font></td>
      </tr>
      <tr bgcolor="#FFFFCC">
        <td><div align="right"><strong><font face="Geneva, Arial, Helvetica, sans-serif">Name of admin file:</font></strong></div></td>
        <td><font face="Geneva, Arial, Helvetica, sans-serif">
          <input name="admin_file" type="text" id="admin_file" value="<?php echo "$admin_file"; ?>">
          <br>
          <font color="#FF0000" size="2">(only if you changed it)</font></font></td>
      </tr>
       <tr bgcolor="#FFFFCC">
	          <td><div align="right"><strong><font face="Geneva, Arial, Helvetica, sans-serif">Name of vwar module folder:</font></strong></div></td>
	          <td><font face="Geneva, Arial, Helvetica, sans-serif">
	            <input name="vwarmodname" type="text" id="vwarmodname" value="<?php echo "$vwarmodname"; ?>">
	            <br>
	            <font color="#FF0000" size="2">(only if you changed it)</font></font></td>
      </tr>
      <tr>
        <td><div align="right"><strong><font face="Geneva, Arial, Helvetica, sans-serif">Graphical Check:</font></strong></div></td>
        <td><font face="Geneva, Arial, Helvetica, sans-serif">
          <select name="gfxchk" id="gfxchk" avlue="<?php echo "$gfx_chk"; ?>">
            <option value="0" selected>No check</option>
            <option value="1">Administrators login only</option>
            <option value="2">Users login only</option>
            <option value="3">New users registration only</option>
            <option value="4">Both, users login and new users registration</option>
            <option value="5">Administrators and users login only</option>
            <option value="6">Administrators and new users registration only </option>
            <option value="7">Everywhere on all login options (Admins and Users)</option>
          </select>
        </font></td>
      </tr>
    </table>
    <input type="submit" name="Submit" value="Submit">
  </div>
</form>
        <?php
        }

        elseif ($errNum==3) die('<span style="font-weight:bold;color:red;">I was able to reach your MySQL server using the MySQL connection settings in your nuke config.php file, but I was unable to reach/locate the database <b>'.$dbname.'</b>. The exact error message that your MySQL server reported is <b>'.mysql_error().'</b>.</span>');
        elseif ($errNum==4) die('<span style="font-weight:bold;color:red;">ERROR!  The exact error message that your MySQL server reported is <b>'.mysql_error().'</b>. Make Sure you have the correct privileges to the database.</span>');
        elseif ($errNum==90) die('<span style="font-weight:bold;color:red;">You have attempted to crack the Installer Script.  All pertinent information for this session has been saved and will be reviewed by the System Administrator and appropriate action will be taken.</span>');
        elseif ($errNum==5) die('<span style="font-weight:bold;color:red;">It aperas that you haven\'t uploaded ALL Installation files. Please upload ALL files located in the INSTALLATION folder.</span>');
        elseif ($errNum==91) die('<span style="font-weight:bold;color:red;">It does not appear that there are any tables to be loaded.  Installation stopped.</span>');
        elseif ($errNum==80) die('<span style="font-weight:bold;color:red;">Unable to update AUTHORS table with random password.  MySQL server reported: '.mysql_error().'. Installation stopped.</span>');
        elseif ($errNum==81) die('<span style="font-weight:bold;color:red;">Unable to update NukeSentinel&trade; Admin table with random password.  MySQL server reported: '.mysql_error().'. Installation stopped.</span>');
}
?>
<hr />
    <p>
      The intent of this Installer is to make the table installation as painless as possible, on both Windows and *nix platforms. Hopefully you will not experience any problems, but if you do, please consult the forums at http://phpnuke-clan.net and if the problem has not yet been reported then please post it. <br>
      If you have gotten to this point, then it appears that your database and config.php file have been setup correctly and the database is ready to be populated with the tables that you will need for PNC&trade; Version <?php echo $pncv ; ?>. Please continue by stepping through the following instructions, in order.
      At the present time you must complete the first 2 steps. We do recommend to get the latest IP2Country version for Sentinel over at: <a href="http://www.nukescripts.net" target="_blank">http://www.nukescripts.net</a>, for better security for your site...
    </p>
    <hr />
    <table>
      <tr>
        <td>
			<?php if( !$_SESSION['pnc'] ){ ?>
				<form method="post" action="<?=$_SERVER['PHP_SELF'];?>">
					<b>Step 1&nbsp;&nbsp;-</b> <input class="c1" type="submit" name="submit" value="Install PNC <?php echo $pncv ; ?> Core Tables" />
					&nbsp;&nbsp;<span class="c3"><?=$_SESSION['pnc'];?></span>
					<input type="hidden" name="op" value="pnc" />
				</form>
            <?php }else{?>
				<form method="post" action="<?=$_SERVER['PHP_SELF'];?>">
					<b>Step 1&nbsp;&nbsp;-</b> <input class="formbutton" type="submit" name="submit" disabled="disabled" value="INSTALLED" />
					&nbsp;&nbsp;<span class="c3"><?=$_SESSION['pnc'];?></span>
					<input type="hidden" name="op" value="pnc" />
				</form>
            <?php } ?>

			<?php if( !$_SESSION['nss'] ){ ?>
				<form method="post" action="<?=$_SERVER['PHP_SELF'];?>">
					<b>Step 2&nbsp;&nbsp;-</b> <input class="c1" type="submit" name="submit" value="Install NukeSentinel&trade; Tables" />
					&nbsp;&nbsp;<span class="c3"><?=$_SESSION['nss'];?></span>
					<input type="hidden" name="op" value="nss" />
				</form>
			<?php }else{?>
				<form method="post" action="<?=$_SERVER['PHP_SELF'];?>">
					<b>Step 2&nbsp;&nbsp;-</b> <input class="formbutton" type="submit" name="submit" disabled="disabled" value="INSTALLED" />
					&nbsp;&nbsp;<span class="c3"><?=$_SESSION['nss'];?></span>
					<input type="hidden" name="op" value="nss" />
				</form>
			<?php } ?>

			<?php if( !$_SESSION['nss_1'] ){ ?>
				<form method="post" action="<?=$_SERVER['PHP_SELF'];?>">
					<b>Step 3&nbsp;&nbsp;-</b> <input class="c1" type="submit" name="submit" value="Install IP2Country Part 1; Tables" />
					&nbsp;&nbsp;<span class="c3"><?=$_SESSION['nss_1'];?></span>
					<input type="hidden" name="op" value="nss_1" />
				</form>
			<?php }else{?>
				<form method="post" action="<?=$_SERVER['PHP_SELF'];?>">
					<b>Step 3&nbsp;&nbsp;-</b> <input class="formbutton" type="submit" name="submit" disabled="disabled" value="INSTALLED" />
					&nbsp;&nbsp;<span class="c3"><?=$_SESSION['nss_1'];?></span>
					<input type="hidden" name="op" value="nss_1" />
				</form>
			<?php } ?>

			<?php if( !$_SESSION['nss_2'] ){ ?>
				<form method="post" action="<?=$_SERVER['PHP_SELF'];?>">
					<b>Step 4&nbsp;&nbsp;-</b> <input class="c1" type="submit" name="submit" value="Install IP2Country Part 2; Tables" />
					&nbsp;&nbsp;<span class="c3"><?=$_SESSION['nss_2'];?></span>
					<input type="hidden" name="op" value="nss_2" />
				</form>
			<?php }else{?>
				<form method="post" action="<?=$_SERVER['PHP_SELF'];?>">
					<b>Step 4&nbsp;&nbsp;-</b> <input class="formbutton" type="submit" name="submit" disabled="disabled" value="INSTALLED" />
					&nbsp;&nbsp;<span class="c3"><?=$_SESSION['nss_2'];?></span>
					<input type="hidden" name="op" value="nss_2" />
				</form>
			<?php } ?>

			<?php if( !$_SESSION['nss_3'] ){ ?>
				<form method="post" action="<?=$_SERVER['PHP_SELF'];?>">
					<b>Step 5&nbsp;&nbsp;-</b> <input class="c1" type="submit" name="submit" value="Install IP2Country Part 3; Tables" />
					&nbsp;&nbsp;<span class="c3"><?=$_SESSION['nss_3'];?></span>
					<input type="hidden" name="op" value="nss_3" />
				</form>
			<?php }else{?>
				<form method="post" action="<?=$_SERVER['PHP_SELF'];?>">
					<b>Step 5&nbsp;&nbsp;-</b> <input class="formbutton" type="submit" name="submit" disabled="disabled" value="INSTALLED" />
					&nbsp;&nbsp;<span class="c3"><?=$_SESSION['nss_3'];?></span>
					<input type="hidden" name="op" value="nss_3" />
				</form>
			<?php } ?>

			<?php if( !$_SESSION['nss_4'] ){ ?>
				<form method="post" action="<?=$_SERVER['PHP_SELF'];?>">
					<b>Step 6&nbsp;&nbsp;-</b> <input class="c1" type="submit" name="submit" value="Install IP2Country Part 4; Tables" />
					&nbsp;&nbsp;<span class="c3"><?=$_SESSION['nss_4'];?></span>
					<input type="hidden" name="op" value="nss_4" />
				</form>
			<?php }else{?>
				<form method="post" action="<?=$_SERVER['PHP_SELF'];?>">
					<b>Step 6&nbsp;&nbsp;-</b> <input class="formbutton" type="submit" name="submit" disabled="disabled" value="INSTALLED" />
					&nbsp;&nbsp;<span class="c3"><?=$_SESSION['nss_4'];?></span>
					<input type="hidden" name="op" value="nss_4" />
				</form>
			<?php } ?>

			<?php if( !$_SESSION['nss_5'] ){ ?>
				<form method="post" action="<?=$_SERVER['PHP_SELF'];?>">
					<b>Step 7&nbsp;&nbsp;-</b> <input class="c1" type="submit" name="submit" value="Install IP2Country Part 5; Tables" />
					&nbsp;&nbsp;<span class="c3"><?=$_SESSION['nss_5'];?></span>
					<input type="hidden" name="op" value="nss_5" />
				</form>
			<?php }else{?>
				<form method="post" action="<?=$_SERVER['PHP_SELF'];?>">
					<b>Step 7&nbsp;&nbsp;-</b> <input class="formbutton" type="submit" name="submit" disabled="disabled" value="INSTALLED" />
					&nbsp;&nbsp;<span class="c3"><?=$_SESSION['nss_5'];?></span>
					<input type="hidden" name="op" value="nss_5" />
				</form>
			<?php } ?>

			<?php if( !$_SESSION['nss_6'] ){ ?>
				<form method="post" action="<?=$_SERVER['PHP_SELF'];?>">
					<b>Step 8&nbsp;&nbsp;-</b> <input class="c1" type="submit" name="submit" value="Install IP2Country Part 6; Tables" />
					&nbsp;&nbsp;<span class="c3"><?=$_SESSION['nss_6'];?></span>
					<input type="hidden" name="op" value="nss_6" />
				</form>
			<?php }else{?>
				<form method="post" action="<?=$_SERVER['PHP_SELF'];?>">
					<b>Step 8&nbsp;&nbsp;-</b> <input class="formbutton" type="submit" name="submit" disabled="disabled" value="INSTALLED" />
					&nbsp;&nbsp;<span class="c3"><?=$_SESSION['nss_6'];?></span>
					<input type="hidden" name="op" value="nss_6" />
				</form>
			<?php } ?>

			<?php if( !$_SESSION['nss_7'] ){ ?>
				<form method="post" action="<?=$_SERVER['PHP_SELF'];?>">
					<b>Step 9&nbsp;&nbsp;-</b> <input class="c1" type="submit" name="submit" value="Install IP2Country Part 7; Tables" />
					&nbsp;&nbsp;<span class="c3"><?=$_SESSION['nss_7'];?></span>
					<input type="hidden" name="op" value="nss_7" />
				</form>
			<?php }else{?>
				<form method="post" action="<?=$_SERVER['PHP_SELF'];?>">
					<b>Step 9&nbsp;&nbsp;-</b> <input class="formbutton" type="submit" name="submit" disabled="disabled" value="INSTALLED" />
					&nbsp;&nbsp;<span class="c3"><?=$_SESSION['nss_7'];?></span>
					<input type="hidden" name="op" value="nss_7" />
				</form>
			<?php } ?>

			<?php if( !$_SESSION['nss_8'] ){ ?>
				<form method="post" action="<?=$_SERVER['PHP_SELF'];?>">
					<b>Step 10&nbsp;-</b> <input class="c1" type="submit" name="submit" value="Install IP2Country Part 8; Tables" />
					&nbsp;&nbsp;<span class="c3"><?=$_SESSION['nss_8'];?></span>
					<input type="hidden" name="op" value="nss_8" />
				</form>
			<?php }else{?>
				<form method="post" action="<?=$_SERVER['PHP_SELF'];?>">
					<b>Step 10&nbsp;-</b> <input class="formbutton" type="submit" name="submit" disabled="disabled" value="INSTALLED" />
					&nbsp;&nbsp;<span class="c3"><?=$_SESSION['nss_8'];?></span>
					<input type="hidden" name="op" value="nss_8" />
				</form>
			<?php } ?>

			<?php if( !$_SESSION['nss_9'] ){ ?>
				<form method="post" action="<?=$_SERVER['PHP_SELF'];?>">
					<b>Step 11&nbsp;-</b> <input class="c1" type="submit" name="submit" value="Install IP2Country Part 9; Tables" />
					&nbsp;&nbsp;<span class="c3"><?=$_SESSION['nss_9'];?></span>
					<input type="hidden" name="op" value="nss_9" />
				</form>
			<?php }else{?>
				<form method="post" action="<?=$_SERVER['PHP_SELF'];?>">
					<b>Step 11&nbsp;-</b> <input class="formbutton" type="submit" name="submit" disabled="disabled" value="INSTALLED" />
					&nbsp;&nbsp;<span class="c3"><?=$_SESSION['nss_9'];?></span>
					<input type="hidden" name="op" value="nss_9" />
				</form>
			<?php } ?>
		</td>
	  </tr>
	</table>
<? if ($_GET['setup']) {echo "<br /><span style=\"color:red;font-weight:bold;font-size:14pt;\">You are now ready to proceed to the Setup/Configuration step. Please select <a href=\"setup.php\">Setup</a> to proceed to the next setup step.</span><br /><br />";

global $prefix,$db,$user_prefix;
function mysql_table_exists($table) {
   $exists = mysql_query("SELECT 1 FROM `$table` LIMIT 0");
   if ($exists) return true;
   return false;
   }
}//end if

?>
    <hr />
    <div class="c1">
      Copyright 2005, 2006 &copy;Raven Web Services<span class="c1"><sup>&trade;</sup></span>, LLC -- All Rights reserved --<br />
      No portion of this document/code may be copied, changed, redistributed, nor reproduced without the written permission of Raven Web Services<span class="c1"><sup>&trade;</sup></span>, LLC
    </div>
    <hr />

<?
// Validate $_POST Data

$isValidOp = FALSE;
$validOp = array('pnc','nss', 'nss_1', 'nss_2', 'nss_3', 'nss_4', 'nss_5', 'nss_6', 'nss_7', 'nss_8', 'nss_9');

if (strlen($_POST['op'])>0 AND (strlen($_POST['op'])==3 OR strlen($_POST['op'])==5)) {
        if (in_array($_POST['op'],$validOp)) {
                $isValidOp = TRUE;
        }
        else {
                rnInstallErr(90);
                die();
        }
}
if (strlen($_POST['submit'])>0 AND $isValidOp) {
        if ($_POST['op']=='pnc') {
                $totalCnt = 0;
                $mtime = microtime();
                $mtime = explode(" ",$mtime);
                $mtime = $mtime[1] + $mtime[0];
                $start_time = $mtime;
                $pncfile = "sql/pnc4.php";
                if (!file_exists($pncfile)) {rnInstallErr(5); die();}
                include("$pncfile");
                $mtime = microtime();
                $mtime = explode(" ",$mtime);
                $mtime = $mtime[1] + $mtime[0];
                $endtime = $mtime;
                $total_time = round(($endtime - $start_time), 4);
                }
        elseif ($_POST['op']=='nss'){
                $totalCnt = 0;
                $mtime = microtime();
                $mtime = explode(" ",$mtime);
                $mtime = $mtime[1] + $mtime[0];
                $start_time = $mtime;
                $pncfile = "sql/pnc4sentinel.php";
                if (!file_exists($pncfile)) {rnInstallErr(5); die();}
				include("$pncfile");
                $mtime = microtime();
                $mtime = explode(" ",$mtime);
                $mtime = $mtime[1] + $mtime[0];
                $endtime = $mtime;
                $total_time = round(($endtime - $start_time), 4);
                }
        elseif ($_POST['op']=='nss_1'){
                $totalCnt = 0;
                $mtime = microtime();
                $mtime = explode(" ",$mtime);
                $mtime = $mtime[1] + $mtime[0];
                $start_time = $mtime;
                $pncfile = "ip2country/ip2country_01.php";
                if (!file_exists($pncfile)) {rnInstallErr(5); die();}
				include("$pncfile");
                $mtime = microtime();
                $mtime = explode(" ",$mtime);
                $mtime = $mtime[1] + $mtime[0];
                $endtime = $mtime;
                $total_time = round(($endtime - $start_time), 4);
				$pncfile = "ip2country/data/ip2country_1.data";
                }
        elseif ($_POST['op']=='nss_2'){
                        $totalCnt = 0;
                $mtime = microtime();
                $mtime = explode(" ",$mtime);
                $mtime = $mtime[1] + $mtime[0];
                $start_time = $mtime;
                $pncfile = "ip2country/ip2country_02.php";
                if (!file_exists($pncfile)) {rnInstallErr(5); die();}
				include("$pncfile");
                $mtime = microtime();
                $mtime = explode(" ",$mtime);
                $mtime = $mtime[1] + $mtime[0];
                $endtime = $mtime;
                $total_time = round(($endtime - $start_time), 4);
				$pncfile = "ip2country/data/ip2country_2.data";
                }
        elseif ($_POST['op']=='nss_3'){
                $totalCnt = 0;
                $mtime = microtime();
                $mtime = explode(" ",$mtime);
                $mtime = $mtime[1] + $mtime[0];
                $start_time = $mtime;
                $pncfile = "ip2country/ip2country_03.php";
                if (!file_exists($pncfile)) {rnInstallErr(5); die();}
				include("$pncfile");
                $mtime = microtime();
                $mtime = explode(" ",$mtime);
                $mtime = $mtime[1] + $mtime[0];
                $endtime = $mtime;
                $total_time = round(($endtime - $start_time), 4);
				$pncfile = "ip2country/data/ip2country_3.data";
                }
        elseif ($_POST['op']=='nss_4'){
                $totalCnt = 0;
                $mtime = microtime();
                $mtime = explode(" ",$mtime);
                $mtime = $mtime[1] + $mtime[0];
                $start_time = $mtime;
                $pncfile = "ip2country/ip2country_04.php";
                if (!file_exists($pncfile)) {rnInstallErr(5); die();}
				include("$pncfile");
                $mtime = microtime();
                $mtime = explode(" ",$mtime);
                $mtime = $mtime[1] + $mtime[0];
                $endtime = $mtime;
                $total_time = round(($endtime - $start_time), 4);
				$pncfile = "ip2country/data/ip2country_4.data";
                }
        elseif ($_POST['op']=='nss_5'){
                $totalCnt = 0;
                $mtime = microtime();
                $mtime = explode(" ",$mtime);
                $mtime = $mtime[1] + $mtime[0];
                $start_time = $mtime;
                $pncfile = "ip2country/ip2country_05.php";
                if (!file_exists($pncfile)) {rnInstallErr(5); die();}
				include("$pncfile");
                $mtime = microtime();
                $mtime = explode(" ",$mtime);
                $mtime = $mtime[1] + $mtime[0];
                $endtime = $mtime;
                $total_time = round(($endtime - $start_time), 4);
				$pncfile = "ip2country/data/ip2country_5.data";
                }
        elseif ($_POST['op']=='nss_6'){
                $totalCnt = 0;
                $mtime = microtime();
                $mtime = explode(" ",$mtime);
                $mtime = $mtime[1] + $mtime[0];
                $start_time = $mtime;
                $pncfile = "ip2country/ip2country_06.php";
                if (!file_exists($pncfile)) {rnInstallErr(5); die();}
				include("$pncfile");
                $mtime = microtime();
                $mtime = explode(" ",$mtime);
                $mtime = $mtime[1] + $mtime[0];
                $endtime = $mtime;
                $total_time = round(($endtime - $start_time), 4);
				$pncfile = "ip2country/data/ip2country_6.data";
                }
        elseif ($_POST['op']=='nss_7'){
                $totalCnt = 0;
                $mtime = microtime();
                $mtime = explode(" ",$mtime);
                $mtime = $mtime[1] + $mtime[0];
                $start_time = $mtime;
                $pncfile = "ip2country/ip2country_07.php";
                if (!file_exists($pncfile)) {rnInstallErr(5); die();}
				include("$pncfile");
                $mtime = microtime();
                $mtime = explode(" ",$mtime);
                $mtime = $mtime[1] + $mtime[0];
                $endtime = $mtime;
                $total_time = round(($endtime - $start_time), 4);
				$pncfile = "ip2country/data/ip2country_7.data";
                }
        elseif ($_POST['op']=='nss_8'){
                $totalCnt = 0;
                $mtime = microtime();
                $mtime = explode(" ",$mtime);
                $mtime = $mtime[1] + $mtime[0];
                $start_time = $mtime;
                $pncfile = "ip2country/ip2country_08.php";
                if (!file_exists($pncfile)) {rnInstallErr(5); die();}
				include("$pncfile");
                $mtime = microtime();
                $mtime = explode(" ",$mtime);
                $mtime = $mtime[1] + $mtime[0];
                $endtime = $mtime;
                $total_time = round(($endtime - $start_time), 4);
				$pncfile = "ip2country/data/ip2country_8.data";
                }
        elseif ($_POST['op']=='nss_9'){
                $totalCnt = 0;
                $mtime = microtime();
                $mtime = explode(" ",$mtime);
                $mtime = $mtime[1] + $mtime[0];
                $start_time = $mtime;
                $pncfile = "ip2country/ip2country_09.php";
                if (!file_exists($pncfile)) {rnInstallErr(5); die();}
				include("$pncfile");
                $mtime = microtime();
                $mtime = explode(" ",$mtime);
                $mtime = $mtime[1] + $mtime[0];
                $endtime = $mtime;
                $total_time = round(($endtime - $start_time), 4);
				$pncfile = "ip2country/data/ip2country_9.data";
                }
else {rnInstallErr(91); die();}

        // MysQL dump comment types
        $comment[0]="#";
        $comment[1]="--";
        $comment[2]="-- ";
        $comment[3]="---";
        $comment[4]="--- ";

        $lines = file (''.$pncfile.'');
        $num_lines = count ($lines);

		if ($isValidOp) {
                if ($_POST['op']=='pnc') {
                        $_SESSION['pnc']='Installed!!! '.$num_lines.' Lines read and added to the database in '. $total_time .'s';
				}
                if ($_POST['op']=='nss') {
                        $_SESSION['nss']='Installed!!! '.$num_lines.' Lines read and added to the database in '. $total_time .'s';
				}
				if ($_POST['op']=='nss_1') {
                        $_SESSION['nss_1']='Installed!!! '.$num_lines.' Lines read and added to the database in '. $total_time .'s';
				}
				if ($_POST['op']=='nss_2') {
                        $_SESSION['nss_2']='Installed!!! '.$num_lines.' Lines read and added to the database in '. $total_time .'s';
				}
				if ($_POST['op']=='nss_3') {
                        $_SESSION['nss_3']='Installed!!! '.$num_lines.' Lines read and added to the database in '. $total_time .'s';
				}
				if ($_POST['op']=='nss_4') {
                        $_SESSION['nss_4']='Installed!!! '.$num_lines.' Lines read and added to the database in '. $total_time .'s';
				}
				if ($_POST['op']=='nss_5') {
                        $_SESSION['nss_5']='Installed!!! '.$num_lines.' Lines read and added to the database in '. $total_time .'s';
				}
				if ($_POST['op']=='nss_6') {
                        $_SESSION['nss_6']='Installed!!! '.$num_lines.' Lines read and added to the database in '. $total_time .'s';
				}
				if ($_POST['op']=='nss_7') {
                        $_SESSION['nss_7']='Installed!!! '.$num_lines.' Lines read and added to the database in '. $total_time .'s';
				}
				if ($_POST['op']=='nss_8') {
                        $_SESSION['nss_8']='Installed!!! '.$num_lines.' Lines read and added to the database in '. $total_time .'s';
				}
				if ($_POST['op']=='nss_9') {
                        $_SESSION['nss_9']='Installed!!! '.$num_lines.' Lines read and added to the database in '. $total_time .'s';
						$setup = true;
				}
                echo "<script>window.location.href = \"".$_SERVER['PHP_SELF']."?setup=$setup\"</script>";
        }
}
?>
</body>
</html>