<SCRIPT>

function blockfix(){
	var input = document.blocker.input.value;
	output = "$content  =  \"";
	for (var c = 0; c < input.length; c++){
		if ((input.charAt(c) == "\n" || input.charAt(c) == "\r")){
			output += "\";";
			if (c != input.length - 1) output +="\n$content  .= \"";
			c++;
			}
		else {
			if (input.charAt(c) == "\"") {
				output += "\\\"";
				}
			else {
				if (input.charAt(c) == "\\"){
					output += "\\\\";
					}
				else {
					output += input.charAt(c);
					if (c == input.length -1) output += "\";";	
					}
				}
			}
		
		}

info="<\?php\n" + 
"#### Generated by Block Creator by Disipal Site (www.disipal.net) ###\n" +
"if (eregi(\"block-Block_Creator.php\",$PHP_SELF)) {\n" + 
"    Header(\"Location: index.php\");\n" + 
"    die();" + 
"\n}\n"
info2="\n?>"

	document.blocker.output.value =info+output+info2;
}

</SCRIPT>