<SCRIPT>

function makemymod(){
	var input = document.modumake.input.value;
	output = "echo\"";
	for (var c = 0; c < input.length; c++){
		if ((input.charAt(c) == "\n" || input.charAt(c) == "\r")){
			output += "\"";
			if (c != input.length - 1) output +="\n  . \"";
			c++;
			}
		else {
			if (input.charAt(c) == "\"") {
				output += "\\\"";
				}
			else {
				if (input.charAt(c) == "\\"){
					output += "\\\\";
					}
				else {
					output += input.charAt(c);
					if (c == input.length -1) output += "\"";	
					}
				}
			}
		
		}

info="<\?php\n" + 
"#### Generated by Module Creator - By Disipal site (www.disipal.net) ####\n" +
"if (!eregi(\"modules.php\", $PHP_SELF)) {\n" + 
"   die (\"You can't access this file directly...\");\n" + 
"\n}\n" +

"require_once(\"mainfile.php\");\n" +
"$module_name = basename(dirname(__FILE__));\n" +
"get_lang($module_name);\n" +
"include(\"header.php\");\n" +
"$index = 0;\n" +
"OpenTable();\n"


info2=";\n" +
"CloseTable();\n" +
"include(\"footer.php\");\n" +
"\n?>";

	document.modumake.output.value =info+output+info2;
}

</SCRIPT>